// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://todwsnxcaiytmdpgrvya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZHdzbnhjYWl5dG1kcGdydnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDY3MTMsImV4cCI6MjA2Nzk4MjcxM30.fbArNjSRUHno8V4mZp4hELH66OOxsWyYYi5DOE_l7RA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});